### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by joschrew**
This PR is part of series to offer single ocrd modules as Docker Containers (ocrd slim containers) to be used with ocr-d network.

### CODE REVIEW

**Review by bertsky — APPROVED** [review]
LGTM.

Will there be another PR with a docker-compose.yml including processing server and processing worker variants?

**Comment by bertsky** [comment]
BTW, I am trying to get the same running for the `maskrcnn-cli` branch (which needs Tensorflow 1.15). I had to steal the recipe for `pip_install_tf1nvidia` from ocrd_all/Makefile for that, and use `ocrd/core-cuda` as base.

Will that be the procedure for the other repos/modules which depend on TF1, too?

**Comment by joschrew** [comment]
1: That is not planed yet. My plan currently is to create a "bigger" docker-compose in ocrd-all with some of the processors and then use that to spin up a processing server and some workers and then run a test-workflow to make sure the processing-workers are working without failure. Similar what we have in core for the dummy worker: https://github.com/OCR-D/core/blob/824a9abc04a304acf0770a359ac69da18f23469b/tests/network/test_processing_server.py#L75-L97. For that test I need this Dockerfile in the first place.
2: Up to now I have only looked at ocrd-cis, ocrd-tessorocr, ocrd-segment, ocrd-olena and ocrd-anybaseocr. I have no idea yet how to create the other Dockerfiles.

**Comment by bertsky** [comment]
Excellent! Regarding 2: I'll do that for all the remaining TF1 modules myself.

**Comment by bertsky** [comment]
BTW, we should also adhere to the following points from the [OCR-D Docker spec](https://ocr-d.de/en/spec/docker):
- volume for /data
- labels
- args for vcs_ref and build_date

**Comment by bertsky** [comment]
While waiting for Docker builds with ocrd_all's `pip_install_tf1nvidia` recipe – i.e. 3x the same, but lots of bandwidth and build time – I got an idea: In core, we should provide a Docker build `ocrd/core-cuda-tf1` (and -tf2 and -torch) in addition to `ocrd/core-cuda` – so that this can be used as (shared!) base layer for respective modules. What do you think @joschrew ?

**Comment by bertsky** [comment]
> Regarding 2: I'll do that for all the remaining TF1 modules myself.

Done! See 
- [ocrd_keraslm](https://github.com/OCR-D/ocrd_keraslm/commit/480a354ef0058244376d4ad66ce3b5802a92df2f)
- [cor-asv-ann](https://github.com/ASVLeipzig/cor-asv-ann/commit/13ffe6472a609cf212670626c5c41d265010b2f5)
- [ocrd_segment:maskrcnn-cli](https://github.com/OCR-D/ocrd_segment/commit/61ee29c593f3463548196f14c90cec7976330433)
- [ocrd_segment here](https://github.com/OCR-D/ocrd_segment/pull/66/commits/11adddfab39c4dd32dc4daff717dae01c2915030) – still draft, but can we merge?

**Comment by bertsky** [comment]
> While waiting for Docker builds with ocrd_all's `pip_install_tf1nvidia` recipe – i.e. 3x the same, but lots of bandwidth and build time – I got an idea: In core, we should provide a Docker build `ocrd/core-cuda-tf1` (and -tf2 and -torch) in addition to `ocrd/core-cuda` – so that this can be used as (shared!) base layer for respective modules. What do you think @joschrew ?

See https://github.com/OCR-D/core/pull/1186

**Comment by joschrew** [comment]
> BTW, we should also adhere to the following points from the [OCR-D Docker spec](https://ocr-d.de/en/spec/docker):

I was not aware of this, thanks for pointing that out, I will add labels, args and volume to my open PR's.

<br/>

> so that this can be used as (shared!) base layer for respective modules. What do you think

I don't know much about the python ml libraries. But I agree that speeding up build times makes sense. I will keep that in mind for the next meeting when things are discussed. I don't see anything against doing this.

<br/>

> * [ocrd_segment here](https://github.com/OCR-D/ocrd_segment/pull/66/commits/
11adddfab39c4dd32dc4daff717dae01c2915030) – still draft, but can we merge?

My tests still work with the updated Dockerfile. So feel free to merge if you think it is ready, I don't think something is missing (but TBH I think I might not notice if it was)

**Comment by bertsky** [comment]
@joschrew if you convert the draft to PR, then I'll merge.

**Pull request merged**
