### PR TITLE
Add a "sanitize" functionality for regions

### PR DESCRIPTION
**Pull request by wrznr**
It expands and/or shrinks regions in such a way that they "closely"
include the lines they contain.

### CODE REVIEW

**Comment by wrznr** [comment]
In:
image

Out:
image


The `convex_hull` function is suboptimal for finding the closest enveloping polygon. Alternatives?

**Comment by wrznr** [comment]
@kba @bertsky @hanfried In desperate need for a review...

**Review by hanfried — COMMENTED** [review]
Can't say much about it, but it's good to see what is going on ...

I only used a bit opencv in past, but of course would be a hassle to manually implement a better algorithm here.
But I would be optimistic to just train a NN for this specific task by creating examples for it artificially:
X (input train data): Own written text (in fracture or w/e font) where we know where we positioned it (so we know the border of the text exactly) plus calculus of convex hull
y (target/labels): output of a more tight more rectangular shape (that we can calculate here as we know the borders of the text line precisely)

Not sure, it smells there should already a solid algorithm existing once we have bounding boxes for every line. Looks for me for a problem other engineering (like chip manufacturing) disciplines have all their day. But I don't have any real clue about.

A completely other way to tackle bad tesseract results would try to predict different tight boundaries (by either different network initializations or just randomly scale up/or down) and then take the best ocr results following a language model probability (might be slow, but for at least it's parallizable). Again we could train it by more or less self augmentation. (Take a known scanned text, find by brute force kind of algorithm a "best fit" bounding polygon (regarding to ocr result of the crop) for enough examples --> train a ML algorithm on it)

Not sure if any of my ideas could be done in the hackathon, might be more a post mortem thing.

**Review by kba — APPROVED** [review]
Looks sensible AFAICS

**Pull request merged**
