### PR TITLE
Add the basic project layout and minimal functionality

### PR DESCRIPTION
**Pull request by wrznr**
This is supposed to be an OCR-D processor which someday will give plausibility feedback on a page's segmentation. It uses https://pypi.org/project/Shapely/ as proposed by @bertsky.

### CODE REVIEW

**Comment by bertsky** [comment]
Thanks for breathing life into this!

Does this minimal functionality reflect a common/specific use case you observed on some pipeline, or is it rather exemplary?

BTW, I found a good explanation of `intersects` vs `overlaps` vs `crosses` [in the manual](https://shapely.readthedocs.io/en/stable/manual.html#binary-predicates), which is much more than in the docstring. It does not say anything on `covers` though.

With the second commit, I can already see this module as going into the more general "layout alignment" (by aligning with itself) – maybe we can ultimately make 2 different processors (sharing the same heuristics), one for evaluation, one for alignment/merging?

**Comment by wrznr** [comment]
@bertsky Could you pls. accept my invitation as a collaborator? Would like to assign you as a reviewer.

> 2 different processors

I do not like the idea. Analytics (and this implementations) would highly overlap. I'd like to control `analyze` vs. `modify` via parameters.

image
This is one of the intended use cases. Happens quite often with tesseract and has a very negative influence on resegment/clip (and ultimately text recognition).

**Comment by bertsky** [comment]
> Could you pls. accept my invitation as a collaborator? Would like to assign you as a reviewer.

Found it.

> > 2 different processors
> 
> I do not like the idea. Analytics (and this implementations) would highly overlap. I'd like to control `analyze` vs. `modify` via parameters.

Yes, I guess there will be too much overlap.

> This is one of the intended use cases. Happens quite often with tesseract and has a very negative influence on resegment/clip (and ultimately text recognition).

Thanks, that's very illustrative! True, this would not work at all with resegment/clip (the rules of which I rather optimised in view of present GT).

**Comment by bertsky** [comment]
This could be very useful for GT as well (example from `buerger_gedichte_1178` page `0002`):

buerger_gedichte_1778 0002 gt-seg-block

**Pull request merged**
